- docs/index.html
> Fix URL. ( docs/index.html )

- js/currency.js
- js/currencyList.js
- package.json
- a0e85ef: 従来の実装では複雑なJSONに対応できないため
- a4221d4: coinhouseの障害が長期化しており適正な価格を取得できないため
> プライスフィードの更新

- component/nem.html
> fix open nem explorer

- js/extension.js
- package-lock.json
> Ethereum Classicが開けない

- component/qrcode.js
QRコードリーダーでAPI呼び出せなくなってたのでたぶんなおした
> qrcode reader bug fix

- js/currency.js
- js/currencyList.js
- package.json
If you use overwinter transaction, assign 3 to txversion in currencyList and
merge https://github.com/karel-3d/bitcoinjs-lib/pull/4 in your repository
> Fix overwinter transaction

- component/txDetail.html
- lang/dict.json
- nao20010128nao/nyaan-wallet@480b598
- nao20010128nao/nyaan-wallet@1b8bf07
> トランザクション詳細でCoinbaseトランザクションが見れるように

- js/currency.js
- js/currencyList.js
- js/explorers/blockbook.js
- js/explorers/index.js
- js/explorers/insight.js
2a61a40048a7f7dc6912a935bad5855146adeb5a はマージ済
> Add Blockbook support

- js/currencyList.js
related https://github.com/monya-wallet/monya/issues/59
> Fix messagePrefix

- js/currencyList.js
VIPSTARCOINのBlockbookが完成したので追加しました。
> Add VIPSTARCOIN Blockbook

- js/explorers/blockbook.js
> fix #65 : change blockbook API balance result

- package.json
> Change to MIT license in package.json

- component/history.html
- component/history.js
- component/utxo.html
- component/utxo.js
- js/store.js
- lang/dict.json
- scss/index.scss
> Display UTXOs for expert use

- js/currencyList.js
> mod fujicoin 1

- component/confirm.html
- component/confirm.js
- component/send.html
- component/send.js
- js/currency.js
- lang/dict.json
- package.json
- scss/index.scss
> Allow sending all funds in the wallet

- component/sweep.html
- component/sweep.js
- js/currency.js
- js/explorers/blockbook.js
- js/explorers/insight.js
- package.json
秘密鍵から吸い出すときの手数料計算をsat/Bで行うようにした
> Use sat/B instead of coins for sweeping

- package-lock.json
- package.json
Signed-off-by: Cryptcoin Junkey <cryptcoin.junkey@gmail.com>
Just updated by running `npm audit fix`.
> Update modules for avoiding vulunerability.

- package-lock.json
- package.json
Signed-off-by: cryptcoin-junkey <cryptcoin.junkey@gmail.com>
> Apply `npm audit fix`.

- js/coinUtil.js
- js/storage.js
* Remove unused arguments.
* Use `reject()` instead of `throw`. See also https://azu.github.io/promises-book/#not-throw-use-reject.
> Refactor promises.

- component/setPassword.js
- js/currency.js
Fix signing message with P2SH-P2WPKH address.
With this, Bitcoin(Segwit) signature can be signed & verified correctly.
> Fix segwit signature bug

- component/finished.js
- component/sweep.html
- component/sweep.js
- js/currency.js
- js/errors.js
- package.json
- "The address could not be derived." loop
- ZEC transaction version 4
- and some refactors to make it safer
> fix several bugs around sweep

- component/ethBase.js
- js/extension.js
- package-lock.json
Fix ethereum node & slight animation change
> Fix Ethereum nodes

- .eslintrc.json
- package.json
scripts methods don't work on windows
* eslint config file has duplicate keys
* grup@3.9.1 don't work on nodejs of version 12 or later. How about version up?
> fix to deploy on windows & other problems

- .eslintrc.json
- js/currency.js
- js/explorers/blockbook.js
- js/explorers/insight.js
> BlockbookExplorerで実装されていなかったgetTxsを実装

- component/confirm.js
> 価格取得失敗しても送金自体はできるように

- js/currencyList.js
discordで質問があった分です
あとの分のコインについては問題ないかと思います
> Use coingecko price(neetcoin)

- js/currencyList.js
既存の1つがダウン
もう1つについてノードを建てた方と連絡がしばらくついていないようです
昔、義理で建てたノードがあるのでdiscord等で、もしヘルプがあった際には追加してください
> Add vips explorer

- js/currencyList.js
btc1.trezor.io -> mainnet-explorer.wakiyamap.dev
> Replace bitcoin explorer

- js/currencyList.js
btc1.trezor.io -> mainnet-explorer.wakiyamap.dev
> Replace Bitcoin(SegWit) explorer
